export const memberSeed = [
  { id: "xinyao", slug: "xinyao-wang", name: "Xinyao Wang", chineseName: "王新尧", group: "faculty", sortOrder: 10, affiliation: "Key Laboratory for Satellite Digitalization Technology, Innovation Academy for Microsatellites of Chinese Academy of Sciences", affiliationUrl: "https://www.microsate.ac.cn/", role: "Faculty Member", roleCn: "教师", email: "wangxinyao@microsate.ac.cn", emailNote: "联系邮箱", homepage: "", orcid: "https://orcid.org/0009-0001-3326-7030", verified: false, research: ["Systems Engineering", "Manned/Unmanned Collaboration", "Computer Vision"], avatar: "/profile-photos/wangxinyao.webp" },
  { id: "zhengwen", slug: "wen-zheng", name: "Wen Zheng", chineseName: "郑文", group: "faculty", sortOrder: 20, affiliation: "Key Laboratory for Satellite Digitalization Technology, Innovation Academy for Microsatellites of Chinese Academy of Sciences", affiliationUrl: "https://www.microsate.ac.cn/", role: "Researcher, Deputy Director", roleCn: "研究员、副主任", email: "zhengwen@microsate.ac.cn", emailNote: "联系邮箱", homepage: "https://microsate.cas.cn/sourcedb/zw/gbzjrc/jcqn/202404/t20240403_7075517.html", orcid: "https://orcid.org/0000-0002-6570-6245", verified: false, research: ["Machine Learning", "AI for Science", "Computer Vision"], avatar: "/profile-photos/zhengwen.webp" },
  { id: "wangrong", slug: "rong-wang", name: "Rong Wang", chineseName: "王蓉", group: "faculty", sortOrder: 30, affiliation: "单位信息待补充", affiliationUrl: "", role: "Faculty Member", roleCn: "教师", email: "邮箱待补充", emailNote: "公开信息待完善", homepage: "", orcid: "", verified: false, research: ["研究领域待补充"], avatar: "/profile-photos/wangrong.webp" },
  { id: "tongtong", slug: "tongtong-shen", name: "Tongtong Shen", chineseName: "申童童", group: "phd", sortOrder: 10, affiliation: "College of Artificial Intelligence, Taiyuan University of Technology", affiliationUrl: "https://www.tyut.edu.cn/", role: "Ph.D. Student in Data Science", roleCn: "数据科学方向博士研究生", email: "2024319017@link.tyut.edu.cn", emailNote: "学校邮箱已验证", homepage: "", orcid: "https://orcid.org/0009-0004-5900-4556", verified: true, research: ["Complex Systems", "Amorphous Materials", "AI for Science"], avatar: "/profile-photos/shentongtong.webp" },
  { id: "zhuohang", slug: "zhuohang-li", name: "Zhuohang Li", chineseName: "李卓杭", group: "phd", sortOrder: 20, affiliation: "单位信息待补充", affiliationUrl: "", role: "Ph.D. Student", roleCn: "博士研究生", email: "邮箱待补充", emailNote: "公开信息待完善", homepage: "", orcid: "https://orcid.org/0009-0007-9834-1370", verified: false, research: ["Computer Vision", "Remote Sensing", "AI for Science"], avatar: "/profile-photos/lizhuohang.webp" },
  { id: "zhaozhao", slug: "zhaozhao-zhang", name: "Zhaozhao Zhang", chineseName: "张召召", group: "phd", sortOrder: 30, affiliation: "单位信息待补充", affiliationUrl: "", role: "Ph.D. Student", roleCn: "博士研究生", email: "邮箱待补充", emailNote: "公开信息待完善", homepage: "", orcid: "", verified: false, research: ["研究领域待补充"], avatar: "/profile-photos/zhangzhaozhao.webp" },
  { id: "yuanyi", slug: "yi-yuan", name: "Yi Yuan", chineseName: "袁易", group: "phd", sortOrder: 40, affiliation: "单位信息待补充", affiliationUrl: "", role: "Ph.D. Student", roleCn: "博士研究生", email: "邮箱待补充", emailNote: "公开信息待完善", homepage: "", orcid: "", verified: false, research: ["研究领域待补充"], avatar: "/profile-photos/yuanyi.webp" },
  { id: "renjie", slug: "renjie-lyu", name: "Renjie Lyu", chineseName: "吕仁杰", group: "phd", sortOrder: 50, affiliation: "单位信息待补充", affiliationUrl: "", role: "Ph.D. Student", roleCn: "博士研究生", email: "邮箱待补充", emailNote: "公开信息待完善", homepage: "", orcid: "", verified: false, research: ["研究领域待补充"], avatar: "/profile-photos/lvrenjie.webp" },
  { id: "yufeng", slug: "yufeng-hao", name: "Yufeng Hao", chineseName: "郝羽丰", group: "phd", sortOrder: 60, affiliation: "单位信息待补充", affiliationUrl: "", role: "Ph.D. Student", roleCn: "博士研究生", email: "邮箱待补充", emailNote: "公开信息待完善", homepage: "", orcid: "", verified: false, research: ["研究领域待补充"], avatar: "/profile-photos/haoyufeng.webp" },
  { id: "junda", slug: "junda-zhu", name: "Junda Zhu", chineseName: "朱骏达", group: "graduate", sortOrder: 10, affiliation: "单位信息待补充", affiliationUrl: "", role: "Graduate Student", roleCn: "研究生", email: "邮箱待补充", emailNote: "公开信息待完善", homepage: "", orcid: "", verified: false, research: ["研究领域待补充"], avatar: "/profile-photos/zhujunda.webp" },
  { id: "benliu", slug: "ben-liu", name: "Ben Liu", chineseName: "刘奔", group: "graduate", sortOrder: 20, affiliation: "单位信息待补充", affiliationUrl: "", role: "Graduate Student", roleCn: "研究生", email: "邮箱待补充", emailNote: "公开信息待完善", homepage: "", orcid: "", verified: false, research: ["研究领域待补充"], avatar: "/profile-photos/liuben.webp" },
  { id: "yongxuan", slug: "yongxuan-tang", name: "Yongxuan Tang", chineseName: "唐镛轩", group: "graduate", sortOrder: 30, affiliation: "单位信息待补充", affiliationUrl: "", role: "Graduate Student", roleCn: "研究生", email: "邮箱待补充", emailNote: "公开信息待完善", homepage: "", orcid: "", verified: false, research: ["研究领域待补充"], avatar: "/profile-photos/tangyongxuan.webp" }
];
